apiVersion: v1
kind: Service
metadata:
  name: solrsvc
  labels:
    app: solr-app
spec:
  type: LoadBalancer
  ports:
  - port: 8983
    name: solr-port
  selector:
    app: solr-app
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata: 
  name: solrapp
  labels:
    app: sts-solr
spec:
  selector:
    matchLabels:
      app: solr-app
  replicas: 3
  podManagementPolicy: Parallel
  serviceName: zk
  template:
    metadata: 
      labels: 
        app: solr-app
    spec:
      securityContext: 
        runAsUser: 8983
        fsGroup: 8983
      containers:
      - name: solr
        image: "solr:6.6-alpine"
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 8983
          name: solr-port
        command: 
        - sh
        - -c
        - solr start -f -c -z zk-0.zk.default.svc.cluster.local:2181,zk-1.zk.default.svc.cluster.local:2181,zk-2.zk.default.svc.cluster.local:2181
